name: API Tests with Allure Report

on:
  push:
    branches: [main]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    services:
      petstore:
        image: swaggerapi/petstore3
        ports:
          - 8080:8080
        options: >-
          --health-cmd="curl -f http://localhost:8080/api/v3/openapi.json || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: cd src/restfulApiTestAutomation && npm install

      - name: Run Playwright API tests
        run: cd src/restfulApiTestAutomation && npx playwright test

      - name: Generate Allure Report
        run: cd src/restfulApiTestAutomation && npx allure generate --clean -o ../../reports/api-e2e

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports/api-e2e