name: Run Android Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  android-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Appium
        run: npm install -g appium

      - name: Install Appium Doctor (optional health check)
        run: npm install -g appium-doctor

      - name: Install Android SDK dependencies
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          force-avd-creation: true
          emulator-options: -no-snapshot -no-audio -no-window
          disable-animations: true
          script: echo "Android emulator setup complete"

      - name: Run Android tests with WebdriverIO
        run: npx wdio run src/mobileAppTestAutomation/appium/config/wdio.android.conf.js

      - name: Generate Allure Report
        run: |
          npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
